# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib MCMS
#' @title a test C++ function
#' @examples
#' data(ENSTest)
#' ENSTestProtein <- Protein(ENSTest)
#' ENSTestModel <- PeptidesModel(ENSTestProtein)
#' # testCpp(slot(ENSTestModel, "c"), slot(ENSTestProtein, "sample.dependency"))
#' testCpp(ENSTestProtein, ENSTestModel)
#' testCpp(ENSTestModel, var.model,
#' 	scale = 1, shape1 = .5, shape2 = .5,
#' 	prior_move_proportion = .02, c_sd = 0.05, o_sd = 0.05, o_k_scale = 1/100)
#' @export
testCpp <- function(aModel, aVarianceModelAsList, scale, shape1, shape2, prior_move_proportion, c_sd, o_sd, o_k_scale) {
    invisible(.Call('MCMS_testCpp', PACKAGE = 'MCMS', aModel, aVarianceModelAsList, scale, shape1, shape2, prior_move_proportion, c_sd, o_sd, o_k_scale))
}

