# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_MCMC_Cpp <- function(aModel, aVarianceModelAsList, n, n_out, burn_in, scale, shape1, shape2, o_restrict, prior_move_proportion, c_sd, o_sd, o_k_scale) {
    .Call('MCMS_run_MCMC_Cpp', PACKAGE = 'MCMS', aModel, aVarianceModelAsList, n, n_out, burn_in, scale, shape1, shape2, o_restrict, prior_move_proportion, c_sd, o_sd, o_k_scale)
}

